### ISSUE TITLE
main libvlc error: No plugins found! Check your VLC installation.

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/VideoLAN-for-Allwinner-A10-VPU#1]
$ ./vlc
VLC media player 2.0.5 Twoflower (revision b408f03)
[0x17de8f0] main libvlc error: No plugins found! Check your VLC installation.

**Comment by matthiasbock** [comment]
http://blog.sleeplessbeastie.eu/2012/05/19/how-to-use-videolan-in-live-mode/

**Comment by matthiasbock** [comment]
export VLC_PLUGIN_PATH=/usr/local/lib/vlc/plugins/

**Comment by matthiasbock** [comment]
ln /usr/local/lib/vlc /usr/lib/vlc -s

**Comment by ashkanm** [comment]
You can go to /usr/bin/ and rename vlc from "vlc" to "vlc1" and copy this script to /usr/bin/
by this method your vlc will be run correctly everytime!
script link: http://ubuntuone.com/6wYBD2rKmr3Z8KcT6mj3Rw
